<?php
require_once __DIR__ . '/../config.php';
$data = jsonInput();
$cedula = inputString($data, 'cedula', 20);
$contrasena = inputString($data, 'contrasena', 255);
if (!preg_match('/^[0-9]+$/', $cedula)) response(['error' => 'La cédula no es válida.'], 400);
$rejected = $pdo->prepare('SELECT id FROM solicitudes_rechazadas WHERE cedula = ?');
$rejected->execute([$cedula]);
if ($rejected->fetch()) response(['error' => 'Los administradores no aprobaron tu petición.'], 403);
$pending = $pdo->prepare("SELECT id FROM usuarios WHERE cedula = ? AND estado = 'pendiente'");
$pending->execute([$cedula]);
if ($pending->fetch()) response(['error' => 'Los administradores todavía no aprobaron tu solicitud de registro.'], 403);
$stmt = $pdo->prepare("SELECT id, nombre, apellido, cedula, correo, password_hash, rol FROM usuarios WHERE cedula = ? AND estado = 'aprobado'");
$stmt->execute([$cedula]);
$user = $stmt->fetch(PDO::FETCH_ASSOC);
if (!$user || !password_verify($contrasena, $user['password_hash'])) response(['error' => 'Credenciales incorrectas.'], 401);
unset($user['password_hash']);
session_regenerate_id(true);
$_SESSION['user'] = $user;
response(['user' => $user]);
